---
- name: install phpinfo
  hosts: all
  become: yes
  tasks:
    - name: install php package on ubuntu
      apt:
        name: php
        state: present
    - name: debug php installed
      ansible.builtin.debug:
        msg: "installed php package"
    - name: copy the info.php file in httpd
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php