---
- name: install lamp on ubuntu
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: install apache2 package
      ansible.builtin.package:
        name: apache2
        state: present

    - name: enable and start apache2 service
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
        state: started

    - name: debug apache2 service started
      ansible.builtin.debug:
        msg: "enabled and started apache2 service"

    - name: install php package
      ansible.builtin.package:
        name: php
        state: present

    - name: debug php package installed
      ansible.builtin.debug:
        msg: "installed php package"
    - name: install libapache2-mod-php package
      ansible.builtin.package:
        name: libapache2-mod-php
        state: present
    - name: debug libapache2-mod-php package installed
      ansible.builtin.debug:
        msg: "installed libapache2-mod-php package"
    - name: restart apache2 to load php module
      ansible.builtin.systemd:
        name: apache2
        state: restarted